global:
  rbac:
    create: false

alertmanager:

  ## Deploy alertmanager
  ##
  enabled: false

grafana:
  enabled: false

prometheus:
  prometheusSpec:
    scrapeInterval: "30s"
    scrapeTimeout: "20s"
    retention: 2d
    storageSpec:
      volumeClaimTemplate:
        spec:
          storageClassName: longhorn
          accessModes: ["ReadWriteOnce"]
          resources:
            requests:
              storage: 5Gi
   
   